apiVersion: v1
kind: Namespace
metadata:
  name: platform
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal
  namespace: platform
spec:
  selector:
    matchLabels:
      app: portal
  replicas: 1
  template:
    metadata:
      labels:
        app: portal
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: platformdata
      volumes:
        - name: platformdata
          hostPath:
            path: /platformdata
---
apiVersion: v1
kind: Service
metadata:
  name: portal
  namespace: platform
spec:
  selector: 
    app: portal
  type: ClusterIP  
  ports:
    - name: http
      port: 80
      targetPort: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: portal
  namespace: platform
spec:
  routes:
    - match: PathPrefix(`/.platform`)
      kind: Rule
      services:
        - name: portal
          port: 80
      middlewares:
        - name: portal-stripprefix
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: portal-stripprefix
  namespace: platform
spec:
  stripPrefix:
    prefixes:
      - "/.platform"
    forceSlash: false